### ISSUE TITLE
What is the ordering scheme of resultant subject biases?

### ISSUE THREAD

**Issue by Qub3k** [Netflix/sureal#38]
Let's say I have an input file using a dictionary to define opinion scores for each stimulus. Let's use as an example, the dictionary given in the README.md file:
```
'os': {'Alice': 40, 'Bob': 45, 'Charlie': 50, 'David': 55, 'Elvis': 60}
```

Now, I apply the `MLE_CO_AP2` model to my input file. As a result, I get a `.json` file. Among other things, it contains subject biases and subject inconsistency scores. Let's say this is the beginning of my output `.json` file (the three dots at the end mean that the file is longer than the snippet presented):
```
{
    "aic": 2.0689578770044244,
    "bic": 2.311378499225354,
    "dof": 0.030222222222222223,
    "loglikelihood": -1.00425671627999,
    "num_iter": 60,
    "observer_bias": [
        0.24779200387111744,
        -0.705541329462216,
        0.3477920038711175,
        -0.29887466279554914,
        -0.31220799612888256
    ],
    ...
}
```

My question is as follows, **what ordering of subjects is used when sureal generates the output file?** Does the first subject bias corresponds to Alice and the last one to Elvis?

I searched the source code and noticed the following function `sureal.tools.misc.get_unique_sorted_list`. **Am I right to assume that sureal always uses a sorted list of unique subject IDs, when generating its output?**

Please note that sureal's documentation does not mention this. Thus, if your input file uses dictionaries to identify which score comes from which subject, it is non-obvious what ordering sureal uses when generating its output. 😌

I would be really glad if any of the maintainers could answer this. I could then generate a pull request with a relevant README.md file update.

**Comment by Qub3k** [comment]
I can already show a very interesting behaviour if we assume that sureal generates its output using a sorted list of unique subject IDs.

I have the following list of opinion scores for some stimulus:
```
'os': {'100': 4, '101': 5, '1100': 4, '121': 5}
```

Our intuition suggests, that this is the sorted list of unique subject IDs: [100, 101, 121, 1100]. However, notice that subject IDs are string literals. Thus, the sorted list of unique subject IDs is as follows: ['100', '101', '1100', '121'].

My point is, that if sureal would keep subject IDs from the input file, when generating its output, this ambiguity would not appear. 😌

**Comment by li-zhi** [comment]
@Qub3k great catch. I would admit that there is a lot to improve in Sureal's input and output format. This is one example. Sureal allows two types of input for 'os' (opinion score): list or dictionary. The semantics should be straightforward for list input since the output is in the same order as the input list. The dictionary input came as an after-thought.

One quick fix to this issue is to also output a subject list using the unique subject IDs, of the same length as the observer_bias. Would you like to give it a shot and submit a PR?

Internally, we are developing a much better new schema. Hopefully one day we will be able to open-source it.

**Comment by slhck** [comment]
@li-zhi Would you consider opening up this process for the community, or is this too far entwined with internal tools, meaning that you cannot afford to have multiple ideas floating around?

I think the idea of a standard notation for subjective data has been brought up multiple times (and Jakub has quite a bit of experience with that), and this might be a good chance for finally finding something universal.

I'd be happy to help write schemata and adapters.

**Comment by li-zhi** [comment]
@slhck Thanks for the interest. At the moment, the schema is coupled with another project. I will have to figure out how to decouple these and carve the part out.

**Comment by Qub3k** [comment]
> One quick fix to this issue is to also output a subject list using the unique subject IDs, of the same length as the observer_bias. Would you like to give it a shot and submit a PR?

@li-zhi I can't promise any deadline, but I will try to implement the quick fix you propose. 😌

I would like to come back to my original question, though. **Do you confirm that sureal's output regarding subject characteristics is sorted using `sureal.tools.misc.get_unique_sorted_list`?**

**Comment by li-zhi** [comment]
@Qub3k yes, I can confirm that get_unique_sorted_list was the function that determines the order of subjects in the final output.

**Comment by li-zhi** [comment]
@Qub3k I found that there existed a way to pull in `observers` field from individual SubjectiveModel classes. I added the field for `MLE_CO_AP2` and there is no need to specifically add the `observer_identifier` field. See more in this commit: https://github.com/Netflix/sureal/commit/877fd2c9d4d7cc25db36bf3fdd803e895fe1824f
