### ISSUE TITLE
Examples and unit tests not working anymore

### ISSUE THREAD

**Issue by JoshuaEbenezer** [Netflix/sureal#43]
Hi,
After the last few updates it seems like the examples and unit tests are failing. I installed the latest version with "pip install sureal" and ran the unit tests and they failed. I also tried running the example script 
`sureal --dataset resource/dataset/lukas_pc_dataset.py --models THURSTONE_MLE BT_MLE \
--plot-dis-videos --output-dir ./output/lukas_pc_dataset`
but got the error message 
`Error: Must have one and only one subclass of SubjectiveModel with type --dataset, but got 0`. I have used sureal in the past without issues so it looks like a recent update has caused a failure.

**Comment by li-zhi** [comment]
@JoshuaEbenezer I forgot to update the Pypi package. That's why it didn't work since when you run `pip install sureal` it installed the older version. Now it's been updated to version 0.7.0. You can install by `pip install -U sureal` and try the cmd again. Let me know if it works.

**Comment by ZaixiS** [comment]
Oh great! Thank you!

**Comment by JoshuaEbenezer** [comment]
Thanks!
